### ISSUE TITLE
Kermits 126: Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by Joseph-Burke** [amita-roy/ROR-Capstone-Her_Style#2]
- There is opportunity to use more semantic HTML tags - a prime example would be exchanging the div that is currently being used as a footer for a footer element.
- The project is off to a great start and it is clearly on its way to being a very well-styled and functional piece of work. Good job on validations. Maybe remove the feature of mailto: the user's own e-mail address.
- Best project ever

**Comment by defoebrand** [comment]
- Be mindful of uploaded images for articles - perhaps use default image if user doesn't upload
- Consider storage service to keep images more permanently
- Look at adjusting component heights to prevent need for vertical scroll
- GREAT JOB!

**Comment by amita-roy** [comment]
Completed all the suggestions hence closing the issue.
